### ISSUE TITLE
typora插入图片的时候会在开头弄一个参数，如何去掉？

### ISSUE THREAD

**Issue by yifengyou** [itcastWsy/typora_copy_images#1]
开头弄得参数Github无法识别，贴图比较麻烦的是没法使用自定义的文件夹，默认只能assets，要改的话就要添加一行没用的参数，大佬应该也注意到了，如何修改默认贴图文件夹？

**Comment by itcastWsy** [comment]
![image](https://user-images.githubusercontent.com/33108189/47267358-56443280-d575-11e8-8a93-32267e8af724.png)
